version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000 #For debug
    command: daphne -b 0.0.0.0 -p 8000 Tesis.asgi:application
    #command: gunicorn -c config/gunicorn/dev.py #For deploy
    volumes:
      - .:/code    
    ports:
      - "8000:8000"
    environment:
      - DEPLOY_ROLE=${DEPLOY_ROLE}
    depends_on:
      - db

