# Generated by Django 3.1.2 on 2021-02-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransmisorESP',
            fields=[
                ('esp_ai_channel', models.CharField(choices=[('Ch00', 'Ch00'), ('Ch01', 'Ch01'), ('Ch02', 'Ch02'), ('Ch03', 'Ch03'), ('Ch04', 'Ch04'), ('Ch05', 'Ch05'), ('Ch06', 'Ch06'), ('Ch07', 'Ch07')], max_length=8)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
