# Generated by Django 3.1.2 on 2021-02-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCADA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmisoresp',
            name='label',
            field=models.CharField(default='', max_length=200),
        ),
    ]
