# Generated by Django 3.1.2 on 2021-02-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCADA', '0003_auto_20210206_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='datapoint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(verbose_name='date published')),
                ('label', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('data', models.CharField(default='0', max_length=20)),
            ],
        ),
    ]
