# Generated by Django 3.2.5 on 2021-10-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCADA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.TextField(default=NameError),
            preserve_default=False,
        ),
    ]
