# Generated by Django 3.2.5 on 2021-10-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCADA', '0003_alter_settings_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='role',
            field=models.CharField(choices=[('HMI', 'HMI'), ('Controller', 'Controller'), ('Master Controller', 'Master Controller')], default='Controller', max_length=17),
        ),
    ]
