# Generated by Django 3.2.5 on 2021-10-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCADA', '0004_alter_settings_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='status',
            field=models.CharField(choices=[('OK', 'OK'), ('COMISSIONED', 'COMISSIONED'), ('UNCOMISSIONED', 'UNCOMISSIONED'), ('FAULT', 'FAULT'), ('OFFLINE', 'OFFLINE')], default='UNCOMISSIONED', max_length=13),
        ),
    ]
